// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	INSTAGRAM_API_BASE_URL: "https://graph.instagram.com/v21.0/";
	DB: D1Database;
}
