name = "telegram-p2p"
compatibility_date = "2024-10-10"

# For Cloudflare Workers
main = "worker/index.ts"
minify = true

# Environment variables
[vars]
INSTAGRAM_API_BASE_URL = "https://graph.instagram.com/v21.0/"

[[d1_databases]]
binding = "DB"
database_name = "telegram-p2p"
database_id = "1bd48c2c-1da1-46b3-ad80-43962c62719b"
