name = "telegram-p2p"
compatibility_date = "2023-10-07"

# For Cloudflare Workers
main = "worker/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "telegram-p2p"
database_id = "1bd48c2c-1da1-46b3-ad80-43962c62719b"
