name = "telegram-p2p"
compatibility_date = "2023-10-07"

# For Cloudflare Workers
main = "worker/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "telegram-p2p"
database_id = "a1639007-789a-4991-82cc-d85382595786"
